import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MyContextProvider } from "../context/CartContext";
import Nav from "./Nav";
import { Poppins } from 'next/font/google';
import './globals.css';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ['400', '700'], // choose weights you want
  subsets: ['latin'], // choose subsets
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  
});

export const metadata = {
  title: "Wn store",
  description: "Generated by create next app",
    icons: {
    icon: "/favicon.ICO", // أو .png
  },

};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MyContextProvider>
          <Nav></Nav>
{children}
        </MyContextProvider>
      </body>
    </html>
  );
}


